version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: katana-forge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: katana
      POSTGRES_PASSWORD: katana
      POSTGRES_DB: katana
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U katana"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: katana-forge-mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: katana-forge-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_started
    env_file:
      - .env.docker
    environment:
      DATABASE_URL: postgresql://katana:katana@postgres:5432/katana?schema=public
      APP_URL: http://localhost:3000
      NEXTAUTH_URL: http://localhost:3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - storage-data:/app/storage/quotes

volumes:
  postgres-data:
  storage-data:
