name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NEXTAUTH_SECRET: test-ci-nextauth-secret
      JWT_SECRET: test-ci-jwt-secret
      NEXTAUTH_URL: http://localhost:3000
      APP_URL: http://localhost:3000
      DATABASE_URL: file:./ci.db
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npx tsc --noEmit --pretty false

      - name: Run unit tests
        run: npm run test:unit

      - name: Build
        run: npm run build

      - name: Package build artifact
        run: |
          mkdir -p dist
          tar -czf dist/katana-forge-${{ github.sha }}.tar.gz \
            .next \
            next.config.js \
            package.json \
            package-lock.json \
            prisma \
            public

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: dist/katana-forge-${{ github.sha }}.tar.gz
          if-no-files-found: error
