name: Release Please
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      upload_url: ${{ steps.release.outputs.upload_url }}
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

  attach-artifacts:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NEXTAUTH_SECRET: release-please-nextauth-secret
      JWT_SECRET: release-please-jwt-secret
      NEXTAUTH_URL: https://example.com
      APP_URL: https://example.com
      DATABASE_URL: file:./release.db
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Package release artifact
        run: |
          mkdir -p dist
          tar -czf dist/katana-forge-${{ needs.release-please.outputs.tag_name }}.tar.gz \
            .next \
            next.config.js \
            package.json \
            package-lock.json \
            prisma \
            public

      - name: Upload build artifact to release
        uses: softprops/action-gh-release@v2
        with:
          upload_url: ${{ needs.release-please.outputs.upload_url }}
          files: |
            dist/katana-forge-${{ needs.release-please.outputs.tag_name }}.tar.gz
            CHANGELOG.md
